### PR TITLE
Added Sampler.GitHubTasks in build.yaml

### PR DESCRIPTION
**Pull request by NicolasBn**
#### Pull Request (PR) description

Edit : There is an issue in AzurePipeline. The deploy job try to found ublish_release_to_GitHub task. But it was present in Sampler.GitHubTasks module which isn't referenced in build.yaml

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/70)

### CODE REVIEW

**Comment by johlju** [comment]
I think you a mistaken. It has not been deprecated. It is used to add a PR for the changelog. Though it can be added after the task that publish module to gallery.

**Comment by johlju** [comment]
You are missing this in the build.yaml
https://github.com/dsccommunity/SqlServerDsc/blob/a9850f2a0d145c15a2a19d23bf20ff670fce17fa/build.yaml#L48-L49

**Comment by NicolasBn** [comment]
Oh ! Indeed ! I forgot to check in Sampler.GitHubTasks module ...
I'll correct this PR.

**Comment by NicolasBn** [comment]
Are the Create_ChangeLog_GitHub_PR task and Publish_GitHub_Wiki_Content task needed?

**Comment by gaelcolas** [comment]
The GitHub PR yes
The GitHub wiki maybe not as the repo might not be ready for it (wiki not created)

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/70#-:-N1IhOmz56TX296WV1tm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NicolasBn)

___
*[`RequiredModules.psd1` line 11 at r2](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/70#-N1Ih6bp8pJ2KC3hPB4F:-N1Ih6bp8pJ2KC3hPB4G:b-cjha4x) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/e5824f33b4b520baf2bf6af83bf8dc246fd5642a/RequiredModules.psd1#L11)):*
> ```PowerShell
>     }
> 
>     'powershell-yaml'           = 'latest'
> ```

Information: This line isn't needed in this file. The bootstrap script make sure this is downloaded. But probably doesn't break anything if it is here as well. :thinking: 



_Code quote:_
```PowerShell
'powershell-yaml'           = 'latest'
```

**Comment by johlju** [comment]
If you are using the latest template files from the `dsccommunity`-template in Sampler you should be able to run the latest ModuleBuilder. But that can be another PR.

**Pull request merged**
