### PR TITLE
Releasing new version with new CI

### PR DESCRIPTION
**Pull request by gaelcolas**
#### Pull Request (PR) description

This updates the CI automation to the DSC community standard, and fixes the HQRM issues.

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50)

### CODE REVIEW

**Comment by gaelcolas** [comment]
Hey @johlju or @PlagueHO, please review this but DO NOT UPDATE the branch.
It's most likely broken because of the git attributes of `*.cab` wasn't set to binary.
If that looks good, I'll force merge to master, and that should be the end of it (and I'll set the branch security to not allow that anymore).

**Review by johlju — CHANGES_REQUESTED** [review]
I could have gone all in on the HQRM style guideline commenting, but left you with some comments that can be resolved throughout the repo. After you resolve these comments I can go through it thoroughly if you like. :smiley:  

> Reviewed 1 of 3 files at r2, 42 of 43 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-:-M0lRG484tY4sXpu-amp:bs3cxg7)* status: all files reviewed, 10 unresolved discussions (waiting on @gaelcolas)

___
*[azure-pipelines.yml, line 52 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lIogF6USjIEVeJARK:-M0lIogGDh5AUF2589Gd:b-3rwjud) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/azure-pipelines.yml#L52)):*
> ```
> 'win1803'
> ```

Should change these build images, but can be done in another PR.
___
*[build.yaml, line 42 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lJ5Cj0y74t_kYEKw8:-M0lJ5Cj0y74t_kYEKw9:bp5cpe) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/build.yaml#L42)):*
> ```YAML
>     - DscResource_Tests_Stop_On_Fail
> ```

We could remove this blank row.
___
*[ReadMe.md, line 1 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lKJuY-aSLTa8Jd0XG:-M0lKJuZ5E1I8oFeQqNz:b-8rk3j5) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/ReadMe.md#L1)):*
> ```Markdown
> # UpdateServicesDsc
> ```

This file name could be changed to upper-case `README.md`. 
___
*[source/DSCResources/MSFT_UpdateServicesApprovalRule/en-US/MSFT_UpdateServicesApprovalRule.strings.psd1, line 16 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lNVKR5okd6X8IX_0L:-M0lNVKR5okd6X8IX_0M:bo3uf4m) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesApprovalRule/en-US/MSFT_UpdateServicesApprovalRule.strings.psd1#L16)):*
> ```
> Test-TargetResource returned false after calling set.
> ```

Non-blocking. We had this text in SqlServerDsc but after he tenth+ issue asking what this meant I change the text to be more descriptive. Suggest doing similar here.

"Test-TargetResource function returned false when Set-TargetResource function verified the desired state. This indicates that the Set-TargetResource did not correctly set the desired state, or that the function Test-TargetResource does not correctly evaluate the desired state."

https://github.com/dsccommunity/SqlServerDsc/blob/209e6e53122d8c10feee6eca098afcc26153f7b4/source/DSCResources/MSFT_SqlSetup/en-US/MSFT_SqlSetup.strings.psd1#L58
___
*[source/DSCResources/MSFT_UpdateServicesServer/en-US/MSFT_UpdateServicesServer.strings.psd1, line 3 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lQZzO0IvO7mMVXm1C:-M0lQZzO0IvO7mMVXm1D:bb39985) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesServer/en-US/MSFT_UpdateServicesServer.strings.psd1#L3)):*
> ```
> TestFailedAfterSet      = Test-TargetResource returned false after calling set.
> ```

Same comment as the previous localization file.
___
*[source/en-US/about_UpdateServicesDsc.help.txt, line 5 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lQgL68_SQmiX9oyMV:-M0lQgL68_SQmiX9oyMW:b3wcjud) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/en-US/about_UpdateServicesDsc.help.txt#L5)):*
> ```
> DSC Resources to manage Update Services (WSUS)
> ```

Add a full stop (`-`) after the sentence.
___
*[source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1, line 172 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lKugh15Bo004TiiAx:-M0lKugi8oWVRaaf_fH1:b58xbxi) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1#L172)):*
> ```
> Where-Object {
> ```

Should be `Where-Object -FilterScript {` if we are going HQRM. Throughout the repo.
___
*[source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1, line 255 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lMZUCBla9MD4AUFQ7:-M0lMZUCBla9MD4AUFQ8:b3fgqun) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1#L255)):*
> ```
> Write-Verbose $script:localizedData.RuleDoNotExist
> ```

This should use named parameters `-Message`.
___
*[source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1, line 255 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lMcrC4lXgZPepRzWT:-M0lMcrC4lXgZPepRzWU:b-8bgcsz) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1#L255)):*
> ```
> Write-Verbose $script:localizedData.RuleDoNotExist
> ```

This localized strings expects the name of the rule to be passed.
___
*[source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1, line 368 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lN638DME_SQOADSCx:-M0lN638DME_SQOADSCy:b-7q4jrt) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1#L368)):*
> ```PowerShell
>         $result = $false
>     }
>     if ($result -and ($ApprovalRule.Ensure -eq "Present"))
> ```

We should put some air in the code so we should add a blank row before each if-block (throughout this file and possible other files)
___
*[source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1, line 26 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lQ3CQ0ijvlQ7YT4vM:-M0lQ3CQ0ijvlQ7YT4vN:b-lszwnx) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1#L26)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> <#
>     .SYNOPSIS
>     Returns the current configuration of WSUS
>     .PARAMETER Ensure
>     Determines if the configuration should be added or removed
> #>
> ```
</details>


We usually write these like this (to have some more air). Throughout the repo.

```powershell
<#
    .SYNOPSIS
        Returns the current configuration of WSUS

    .PARAMETER Ensure
        Determines if the configuration should be added or removed
#>
```
___
*[source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1, line 36 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lPysxCEmqk8uai3fJ:-M0lPysxCEmqk8uai3fK:bvr3iw2) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1#L36)):*
> ```
> "Present","Absent"
> ```

We can use single-quotes here. Resolves to single-quotes throughout this file (and possible other resources code in the repo) 
___
*[source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1, line 632 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lPXyI0br2AIPXh8Z6:-M0lPXyI0br2AIPXh8Z7:bz61aw4) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1#L632)):*
> ```
> !
> ```

We can change this to `-not` to be consequent. Throughout (if there are more).
___
*[source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1, line 791 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lPqu0AKUMRe2Uqm5t:-M0lPqu0AKUMRe2Uqm5u:bf113td) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1#L791)):*
> ```
> if ($result -and ($Wsus.Ensure -eq "Present"))
> ```

We can get some air in the code by adding blank row after each if block
___
*[source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1, line 791 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lPuC548fXHVMEZRZf:-M0lPuC66NEgcpmXvTJR:byk3955) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1#L791)):*
> ```
> "Present"
> ```

We can use single-quotes here.
___
*[source/en-US/UpdateServices.strings.psd1, line 6 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lQpay-zGWzRY0K5Xz:-M0lQpay-zGWzRY0K5Y-:b-sdzf94) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/en-US/UpdateServices.strings.psd1#L6)):*
> ```
> TestFailedAfterSet
> ```

Same comment as in previous localization file.

**Comment by johlju** [comment]
I updated the labels for this repo.

**Review by gaelcolas — COMMENTED** [review]
I hope there's no more blocking issues as I won't get much time before Community call.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-:-M0m1eoXCGGUTYMprhzJ:b4c4o3p)* status: 36 of 44 files reviewed, 10 unresolved discussions (waiting on @johlju)

___
*[azure-pipelines.yml, line 52 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lIogF6USjIEVeJARK:-M0lm6va1UVzvBPXEbti:be2r6xp) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/azure-pipelines.yml#L52)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 'win1803'
> ```

Should change these build images, but can be done in another PR.
</blockquote></details>

Change to what? I just copy pasted from guidelines tbh.
___
*[build.yaml, line 42 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lJ5Cj0y74t_kYEKw8:-M0lmCS29XBlyRIBKSB_:bb7f2mf) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/build.yaml#L42)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We could remove this blank row.
</blockquote></details>

done
___
*[ReadMe.md, line 1 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lKJuY-aSLTa8Jd0XG:-M0lmP29CPRTuJbh_XFG:bcytw8t) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/ReadMe.md#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This file name could be changed to upper-case `README.md`. 
</blockquote></details>

done (I think)
___
*[source/DSCResources/MSFT_UpdateServicesApprovalRule/en-US/MSFT_UpdateServicesApprovalRule.strings.psd1, line 16 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lNVKR5okd6X8IX_0L:-M0lx1v6EbrjEe41Ay6o:bdl4lep) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesApprovalRule/en-US/MSFT_UpdateServicesApprovalRule.strings.psd1#L16)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Test-TargetResource returned false after calling set.
> ```

Non-blocking. We had this text in SqlServerDsc but after he tenth+ issue asking what this meant I change the text to be more descriptive. Suggest doing similar here.

"Test-TargetResource function returned false when Set-TargetResource function verified the desired state. This indicates that the Set-TargetResource did not correctly set the desired state, or that the function Test-TargetResource does not correctly evaluate the desired state."

https://github.com/dsccommunity/SqlServerDsc/blob/209e6e53122d8c10feee6eca098afcc26153f7b4/source/DSCResources/MSFT_SqlSetup/en-US/MSFT_SqlSetup.strings.psd1#L58

</blockquote></details>

I think a lot of the error messages need improvement. So far I only moved them to language file, so I'll leave that aside for now.
___
*[source/en-US/about_UpdateServicesDsc.help.txt, line 5 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lQgL68_SQmiX9oyMV:-M0m1Y0z8J11uXWjGXbH:b-896fix) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/en-US/about_UpdateServicesDsc.help.txt#L5)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> DSC Resources to manage Update Services (WSUS)
> ```

Add a full stop (`-`) after the sentence.
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1, line 172 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lKugh15Bo004TiiAx:-M0lmml39Ga_LLfHLRWq:bb7f2mf) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1#L172)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Where-Object {
> ```

Should be `Where-Object -FilterScript {` if we are going HQRM. Throughout the repo.
</blockquote></details>

done
___
*[source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1, line 255 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lMZUCBla9MD4AUFQ7:-M0lqcdX3_hTfr0LGjWj:bb6un1j) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1#L255)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Write-Verbose $script:localizedData.RuleDoNotExist
> ```

This should use named parameters `-Message`.
</blockquote></details>

Done
___
*[source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1, line 255 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lMcrC4lXgZPepRzWT:-M0lvan56g6-ID8gKREv:bb6un1j) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1#L255)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Write-Verbose $script:localizedData.RuleDoNotExist
> ```

This localized strings expects the name of the rule to be passed.
</blockquote></details>

Done
___
*[source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1, line 368 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lN638DME_SQOADSCx:-M0lvZ1l45HJtlvbkr2t:b-3lqan7) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesApprovalRule/MSFT_UpdateServicesApprovalRule.psm1#L368)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should put some air in the code so we should add a blank row before each if-block (throughout this file and possible other files)
</blockquote></details>

Done (I think)
___
*[source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1, line 26 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lQ3CQ0ijvlQ7YT4vM:-M0lzZlo9WsLbMFZ_zEv:b-896fix) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1#L26)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> <#
>     .SYNOPSIS
>     Returns the current configuration of WSUS
>     .PARAMETER Ensure
>     Determines if the configuration should be added or removed
> #>
> ```

We usually write these like this (to have some more air). Throughout the repo.

```powershell
<#
    .SYNOPSIS
        Returns the current configuration of WSUS

    .PARAMETER Ensure
        Determines if the configuration should be added or removed
#>
```
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1, line 36 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lPysxCEmqk8uai3fJ:-M0m0kK-5RgjESIhPp7N:b-896fix) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1#L36)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> "Present","Absent"
> ```

We can use single-quotes here. Resolves to single-quotes throughout this file (and possible other resources code in the repo) 
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1, line 632 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lPXyI0br2AIPXh8Z6:-M0m17hl-C_UyI-4vQJu:b-896fix) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1#L632)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> !
> ```

We can change this to `-not` to be consequent. Throughout (if there are more).
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1, line 791 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lPqu0AKUMRe2Uqm5t:-M0m19FK49YJ758o19Rj:b-896fix) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1#L791)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($result -and ($Wsus.Ensure -eq "Present"))
> ```

We can get some air in the code by adding blank row after each if block
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1, line 791 at r4](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-M0lPuC548fXHVMEZRZf:-M0m1ALf-UamIAkGgleB:b-896fix) ([raw file](https://github.com/dsccommunity/updateservicesdsc/blob/269845eca120f44babd351ba083c8c585eb4f62e/source/DSCResources/MSFT_UpdateServicesServer/MSFT_UpdateServicesServer.psm1#L791)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> "Present"
> ```

We can use single-quotes here.
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/50#-:-M0st0uw6tvGs3yXfk-S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
This is good enough! 😃 Awesome work! I leave this one for you to merge (or force push as you mentioned).

**Pull request merged**
