### PR TITLE
Fix tests, minor style issues, offline CAB update

### PR DESCRIPTION
**Pull request by Borgquite**
#### Pull Request (PR) description
@johlju Have started work on this module with a lot of small ‘cleanup’ tasks.

Hopefully there’s no argument over these changes - gets the tests working, fixes some dodgy strings, updates the offline CAB, adds some additional Classification GUIDs to the notes for convenience. It should hopefully be a quick and easy one for review & approval :)

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/UpdateServicesDsc/80)

### CODE REVIEW

**Comment by Borgquite** [comment]
@johlju Are you able to take a look at this sometime please?

**Comment by johlju** [comment]
When I have time I will take a look. 🙂

**Review by johlju — COMMENTED** [review]
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/UpdateServicesDsc/80)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @Borgquite)

___
*[`source/DSCResources/MSFT_UpdateServicesServer/WSUS.cab` line 0 at r1](https://reviewable.io/reviews/dsccommunity/UpdateServicesDsc/80#-O1qh2ou1KIyBe7bV8tr:-O1qh2ov5SuEscOFmtZg:b1eri4s) ([raw file](https://github.com/dsccommunity/UpdateServicesDsc/blob/bec2754eb1d2909beead9e118f04a540726a4eea/source/DSCResources/MSFT_UpdateServicesServer/WSUS.cab#L0)):*
Why do we need to change this file? What is it used for? Since the content of the file cannot be reviewed, what would it take to update this file in the pipeline, so that the pipeline installs the correct things and add the correct file to the package?

**Review by Borgquite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/UpdateServicesDsc/80)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[`source/DSCResources/MSFT_UpdateServicesServer/WSUS.cab` line  at r1](https://reviewable.io/reviews/dsccommunity/UpdateServicesDsc/80#-O1qh2ou1KIyBe7bV8tr:-O1qpvdg8xR2S6lze2t2:b-sl2xd9) ([raw file](https://github.com/dsccommunity/UpdateServicesDsc/blob/bec2754eb1d2909beead9e118f04a540726a4eea/source/DSCResources/MSFT_UpdateServicesServer/WSUS.cab#L)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Why do we need to change this file? What is it used for? Since the content of the file cannot be reviewed, what would it take to update this file in the pipeline, so that the pipeline installs the correct things and add the correct file to the package?
</blockquote></details>

It's a current export of Microsoft's WSUS product metadata. The contents can be reviewed, but not automatically through Reviewable - just download, extract, and look at the before/after XML files.

The purpose of the file and how it is generated is documented here:
https://learn.microsoft.com/en-us/mem/configmgr/sum/get-started/synchronize-software-updates-disconnected

But the basics are - it allows the WSUS server to be set up offline without requiring connectivity to Microsoft Update. The process is:
1. Choose a WSUS server that is synchronized with Microsoft Update by using the software update classifications, products, and languages that you need in your Configuration Manager environment. (FOR THE PURPOSE HERE, I set up a fully patched Windows Server 2022 Standard VM with *all* classifications, products and languages).
2. Perform a sync
3. Run wsusutil.exe export packagename logfilename
4. Grab a copy of the packagename

I found that without the updated version, I was unable to configure a new WSUS server to synchronise new products that came out since the last update (e.g. 'Windows Admin Center'). The CAB needs to be periodically updated (as far as I can see, this has been done before in the lifetime of this module).

I did look to see if the Microsoft published and regularly updated Windows Update offline scan file, [Wsusscan2.cab](http://go.microsoft.com/fwlink/?linkid=74689), could be used instead (see below). This would make your pipeline suggestion feasable. However, the contents of that file do not match the output of 'wsusutil.exe export' generated in the above process.

https://support.microsoft.com/en-gb/topic/a-new-version-of-the-windows-update-offline-scan-file-wsusscn2-cab-is-available-for-advanced-users-fe433f4d-44f4-28e3-88c5-5b22329c0a08

**Comment by johlju** [comment]
Thanks for the detailed explanation! 🙂  So to be able to do this in the pipeline, we would have to install a WSUS server, sync it to MS Update and [configure the new classifications and products](https://learn.microsoft.com/en-us/mem/configmgr/sum/get-started/configure-classifications-and-products) then run the command. Would it be feasible to do all that without user intervention for each deploy in Azure Pipelines on a Win2022 Server build worker within its 4 hour run time?

**Review by johlju — APPROVED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/UpdateServicesDsc/80)* status: all files reviewed, 1 unresolved discussion (waiting on @Borgquite)

___
*[`source/DSCResources/MSFT_UpdateServicesServer/WSUS.cab` line  at r1](https://reviewable.io/reviews/dsccommunity/UpdateServicesDsc/80#-O1qh2ou1KIyBe7bV8tr:-O1v44jpCKhqx5qVKvJo:bazezkx) ([raw file](https://github.com/dsccommunity/UpdateServicesDsc/blob/bec2754eb1d2909beead9e118f04a540726a4eea/source/DSCResources/MSFT_UpdateServicesServer/WSUS.cab#L)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

It's a current export of Microsoft's WSUS product metadata. The contents can be reviewed, but not automatically through Reviewable - just download, extract, and look at the before/after XML files.

The purpose of the file and how it is generated is documented here:
https://learn.microsoft.com/en-us/mem/configmgr/sum/get-started/synchronize-software-updates-disconnected

But the basics are - it allows the WSUS server to be set up offline without requiring connectivity to Microsoft Update. The process is:
1. Choose a WSUS server that is synchronized with Microsoft Update by using the software update classifications, products, and languages that you need in your Configuration Manager environment. (FOR THE PURPOSE HERE, I set up a server with *all* classifications, products and languages).
2. Perform a sync
3. Run wsusutil.exe export packagename logfilename
4. Grab a copy of the packagename

I found that without the updated version, I was unable to configure a new WSUS server to synchronise new products that came out since the last update (e.g. 'Windows Admin Center'). The CAB needs to be periodically updated (as far as I can see, this has been done before in the lifetime of this module).

I did look to see if the Microsoft published and regularly updated Windows Update offline scan file, Wsusscan2.cab, could be used instead (see below). This would make your pipeline suggestion feasable. However, the contents of that file do not match the output of 'wsusutil.exe export' generated in the above process.

https://support.microsoft.com/en-gb/topic/a-new-version-of-the-windows-update-offline-scan-file-wsusscn2-cab-is-available-for-advanced-users-fe433f4d-44f4-28e3-88c5-5b22329c0a08
</blockquote></details>

Thanks for the detailed explanation! 🙂  So to be able to do this in the pipeline, we would have to install a WSUS server, sync it to MS Update and [configure the new classifications and products](https://learn.microsoft.com/en-us/mem/configmgr/sum/get-started/configure-classifications-and-products) then run the command. Would it be feasible to do all that without user intervention for each deploy in Azure Pipelines on a Win2022 Server build worker within its 4 hour run time?

**Comment by johlju** [comment]
The diff of the .cab file is so large so it is not feasible to review it, I have to assume it is correct and valid. 🙂

**Comment by johlju** [comment]
I added issue #81 to track if there is a way to automate generating the .cab file.

**Review by Borgquite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/UpdateServicesDsc/80)* status: all files reviewed, 1 unresolved discussion

___
*[`source/DSCResources/MSFT_UpdateServicesServer/WSUS.cab` line  at r1](https://reviewable.io/reviews/dsccommunity/UpdateServicesDsc/80#-O1qh2ou1KIyBe7bV8tr:-O1w-EiyCKnUIv1sG3VX:boq8nee) ([raw file](https://github.com/dsccommunity/UpdateServicesDsc/blob/bec2754eb1d2909beead9e118f04a540726a4eea/source/DSCResources/MSFT_UpdateServicesServer/WSUS.cab#L)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Thanks for the detailed explanation! 🙂  So to be able to do this in the pipeline, we would have to install a WSUS server, sync it to MS Update and [configure the new classifications and products](https://learn.microsoft.com/en-us/mem/configmgr/sum/get-started/configure-classifications-and-products) then run the command. Would it be feasible to do all that without user intervention for each deploy in Azure Pipelines on a Win2022 Server build worker within its 4 hour run time?
</blockquote></details>

No worries! I *think* this would be possible, as the initial sync takes minutes, not hours. Not something I'd be keen to do myself, but I can't see why it couldn't be done...

**Review by Borgquite — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/UpdateServicesDsc/80#-:-O1wCWLQAIFcAdyqIdWv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
