### PR TITLE
Update offline package export

### LINKED ISSUE #51: UpdateServicesServer: WSUS.cab file is missing products
#### Details of the scenario you tried and the problem that is occurring
The initial sync `WSUS.cab` file is out of date and is missing `Windows Server 2019` and other products.

The following snippet fails because `Windows Server 2019` is not a known product.
```
UpdateServicesServer 'UpdateServices' {
  Synchronize = $false # Default, use WSUS.cab
  Products = @(
    'Windows Server 2019'
  )
 ...
```

#### Verbose logs showing the problem
```
[[UpdateServicesServer]UpdateServices] Products test failed
[[UpdateServicesServer]UpdateServices] Test-TargetResouce returned false after calling set. | ErrorType: MSFT_UpdateServicesServer.TestFailedAfterSet
```

After a full sync, `Windows Server 2019` product can be used.

#### Suggested solution to the issue
Please update bundled WSUS metadata export in `WSUS.cab`

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
See above.
```

#### The operating system the target node is running
Windows Server 2019

#### Version and build of PowerShell the target node is running
5.1.17763.1007

#### Version of the DSC module that was used
UpdateServicesDsc 1.1.0.0

### PR DESCRIPTION
**Pull request by Firefishy**
#### Pull Request (PR) description
Update the initial WSUS offline export/import package

```CreationTime="2015-06-10T16:47:55Z" FormatVersion="1.0" ProtocolVersion="1.8"```
to
```CreationTime="2020-04-21T23:50:06Z" FormatVersion="1.0" ProtocolVersion="1.20"```

#### This Pull Request (PR) fixes the following issues
Fixes #51

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/52)

### CODE REVIEW

**Comment by Firefishy** [comment]
@johlju @gaelcolas This should be ready for review.

**Comment by gaelcolas** [comment]
Sorry I missed that. If I don't update within a week please come to the DSC channel in slack, I get about 100 notifications everyday so I miss a ton of those... :/

**Review by gaelcolas — DISMISSED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/52)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by gaelcolas — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/updateservicesdsc/52)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
